[sources.filesystem] # use [sources.readers.credentials] for the "readers" source
bucket_url="../../raw/"
file_glob="*"

[destination.postgres]
dataset_name = "raw"

[destination.postgres.credentials]
drivername = "postgresql+psycopg2"
database = "postgres" 
password = "postgres" 
username = "postgres" 
host = "localhost"
port = 5432
connect_timeout = 15